export const SANDRA_DELIVERY_REQUEST_TIMEOUT_MS = 3_000;
export const SANDRA_DELIVERY_MAX_ATTEMPTS = 2;
export const SANDRA_DELIVERY_SWEEP_BATCH_SIZE = 6;
export const SANDRA_DELIVERY_CRON_MAX_DURATION_SECONDS = 60;
export const SANDRA_DELIVERY_CRON_HEADROOM_SECONDS = 10;
