#!/bin/zsh
# Lesson 8A base plates — one lane per image: zsh gen_stills_8A.sh <key>
# Pattern copied from gen_stills_7A.sh. Anchors in course-assets/scenes/module-08/_anchors/
# (jim/mark/david copied from 7A; ray/carol/marcus/grace cropped from cast-board, text sliver trimmed).
set -u
cd "/Users/jarradhenry/Sites/BMH apps/BMH Institute"
D="docs/design"
A="course-assets/scenes/module-08/_anchors"
AV="course-assets/avatar-candidates"
OUT="course-assets/scenes/module-08"
mkdir -p "$OUT"
STYLE='STYLE: flat sticker-sheet illustration, thick black hand-drawn outlines with a slight wobble, rounded corners, flat fills only (yellow, orange, cream, white, black) on cornflower-blue background, no gradients, no texture, no shadows, no lighting, no perspective. Tiny dot eyes, minimal facial features, cylindrical limbs, strong simple silhouettes. Confidently imperfect, hand-drawn. No skin-tone shading. No text or words anywhere. No floating hearts, sparkles, notes, thought bubbles, or motion marks. 16:9 composition, 1600x900.'
NEG='NEGATIVE: no clone, no duplicate person, no second copy of the character, no extra people, no photorealism, no 3D, no shading, no gradient, no readable text.'

ANDREA='IDENTICAL to the attached ANDREA reference: a friendly woman with shoulder-length wavy black hair, tiny black dot eyes, tiny simple nose, small simple smile. Keep her face and hair exactly as the reference. NO headset in this scene.'
ANDREA_SWIM='IDENTICAL to the attached ANDREA reference: a friendly woman with shoulder-length wavy black hair, tiny black dot eyes, tiny simple nose, small simple smile. Keep her FACE and HAIR exactly as the reference, but her outfit here is a simple flat one-piece SWIMSUIT in mustard-YELLOW with a thin orange trim stripe — no long-sleeve top, no pants, just the swimsuit, bare arms and legs (flat white/cream limbs, no skin-tone shading, matching the reference art style). NO headset in this scene.'
JIM='IDENTICAL to the attached JIM reference: a friendly balding man with round orange goggles pushed up on his forehead, a mustard-YELLOW collared polo shirt, cream pants, orange shoes, tiny black dot eyes, simple bracket nose, small smile. Keep his face, hair, goggles and outfit exactly as the reference.'
MARK='IDENTICAL to the attached MARK reference: a young man with short black hair, an ORANGE t-shirt, yellow pants, cream shoes, tiny black dot eyes, simple bracket nose. Keep his face, hair and outfit exactly as the reference.'
DAVID='IDENTICAL to the attached DAVID reference: a heavyset older man, bald on top with a full grey beard, an ORANGE long-sleeve shirt, yellow pants, orange shoes, tiny black dot eyes. Keep his face, beard and outfit exactly as the reference.'
RAY='IDENTICAL to the attached RAY reference: a slim young man with short curly black hair, an ORANGE t-shirt, cream pants, yellow shoes, tiny black dot eyes, simple nose. Keep his face, hair and outfit exactly as the reference.'
CAROL='IDENTICAL to the attached CAROL reference: a middle-aged woman with a grey bob haircut, a mustard-YELLOW long-sleeve top, orange pants, cream shoes, tiny black dot eyes. Keep her face, hair and outfit exactly as the reference.'
MARCUS='IDENTICAL to the attached MARCUS reference: a young man with short curly black hair, a mustard-YELLOW sweater, cream pants, orange shoes, tiny black dot eyes. Keep his face, hair and outfit exactly as the reference.'
GRACE='IDENTICAL to the attached GRACE reference: an elderly woman with grey hair in a bun, round glasses, an ORANGE cardigan over a cream dress, tiny dot eyes behind the glasses. Keep her face, hair, glasses and outfit exactly as the reference.'

gen() {
  local file="$1"; local anchor="$2"; local ident="$3"; local desc="$4"
  echo "=== GEN $file ==="
  echo "Generate one image with gpt-image-2 and save it to $OUT/$file (PNG, 1600x900). Match the attached style references exactly and keep the character IDENTICAL to the attached character reference. CHARACTER: $ident COMPOSITION: $desc $STYLE $NEG" | \
  codex exec -i "$D/style-ref-1.png" -i "$D/style-ref-2.png" -i "$anchor" --skip-git-repo-check --sandbox workspace-write 2>&1 | tail -3
  [ -f "$OUT/$file" ] && echo "OK $file" || echo "MISSING $file"
}

case "$1" in
andrea_beach)
  # v2 (Jarrad note): SWIMSUIT, not the long-sleeve top + pants — v1 looked weird in beach setting.
  gen "m08_L8A_andrea-beach.png" "$AV/andrea_headset_v2.png" "$ANDREA_SWIM" "EXACTLY ONE person: ANDREA relaxing at the beach in her swimsuit, sitting comfortably in a simple doodle beach lounge chair, facing the camera directly, head upright, full face clearly visible, relaxed happy expression, hands resting easy on the chair arms. Behind her a wide cream-colored sand strip along the bottom, a large orange-and-white beach umbrella planted beside the chair, a simple wavy sea line and one or two flat doodle waves in the cornflower-blue background, a small yellow sun high in the sky. Composition centered on Andrea, her head and shoulders prominent in the middle of the frame with generous open sky around. EXACTLY ONE PERSON." ;;
b02_weight)
  gen "m08_L8A_b02_weight.png" "$A/jim.png" "$JIM" "EXACTLY ONE person: JIM standing, holding a single huge tangled black knot of rope above his head with both arms — the knot is one giant messy ball of thick tangled line, clearly heavy. His knees are slightly bent under the weight but his expression is calm and determined. Standing on a simple ground line, centered, generous open cornflower-blue space around. EXACTLY ONE PERSON." ;;
b03_underwater)
  # v4 (Jarrad note): "cellar" in the earlier note was a mis-transcription of "MARCUS" — HE must be underwater too, not standing on dry ground.
  gen "m08_L8A_b03_underwater.png" "$A/marcus.png" "$MARCUS" "EXACTLY ONE person: MARCUS AND the simple doodle house beside him are BOTH standing in flood water — this is ONE single continuous body of water with ONE flat water surface, so the SAME horizontal wavy WATER line crosses BOTH Marcus's body AND the house at the SAME height in the image. That one wavy line sits at upper-window height on the house (near the top of the house body, just below the roofline) and crosses MARCUS at his neck/shoulders (since he is standing right beside the house, his much shorter body is submerged nearly up to his neck by that same water level). Everything below that single line — most of Marcus's body, the house's upper window, door, and lower window — is submerged and tinted muted underwater-blue. Only Marcus's head/shoulders and the house's roof, chimney, and gutter line stay above the water in normal palette colors. THERE IS ONLY ONE WAVY LINE IN THE ENTIRE IMAGE, and it is perfectly level/horizontal all the way across, passing through both Marcus and the house at the same height — no second wave line, no ripples, no other wavy marks anywhere. Marcus's worried face and one hand on his head are visible above the water; his expression is worried, looking at the house. Centered composition, generous open cornflower-blue space around. EXACTLY ONE PERSON." ;;
b04_response)
  gen "m08_L8A_b04_response.png" "$A/marcus.png" "$MARCUS" "EXACTLY ONE person: MARCUS seated at a simple kitchen table, a smartphone held to his ear, several flat paper documents spread on the table in front of him, his posture easing and his expression relieved, mid-conversation. Scene composed in the LEFT and CENTER of the frame; keep the bottom-right corner area completely empty cornflower-blue (space reserved for a circle overlay). EXACTLY ONE PERSON." ;;
b05_tenants)
  gen "m08_L8A_b05_tenants.png" "$A/david.png" "$DAVID" "EXACTLY THREE people: DAVID standing in the front yard of a simple two-story doodle duplex house, gesturing toward it with one open hand. In the open front doorway of the duplex stand a young couple — a man and a woman in simple doodle style (cream and orange clothing, tiny dot eyes) — standing together as the tenants. DAVID is the large foreground figure; the couple is smaller in the doorway. Centered composition. EXACTLY THREE PEOPLE, no more." ;;
b06_squatters)
  gen "m08_L8A_b06_squatters.png" "$A/mark.png" "$MARK" "EXACTLY ONE full person: MARK standing outside a simple doodle house, arms crossed tightly, frustrated expression, looking at the house. In one window of the house there is a plain solid-black SILHOUETTE shape of a person — just a flat black shape, no features. The house has one board nailed across a lower window. Centered composition, generous open cornflower-blue space around. EXACTLY ONE full person plus one flat black window silhouette." ;;
b07_leaseback)
  gen "m08_L8A_b07_leaseback.png" "$A/grace.png" "$GRACE" "EXACTLY ONE person: GRACE the elderly woman sitting comfortably in her yellow armchair inside her living room, holding her teacup, content expression. Beside the armchair are two or three stacked flat cardboard-kraft moving boxes, packed and closed. On a small side table next to her sits a single large door key. Scene composed in the LEFT and CENTER of the frame; keep the bottom-right corner area completely empty cornflower-blue (space reserved for a circle overlay). EXACTLY ONE PERSON." ;;
b08_privacy)
  # v4 (Jarrad note): v3 STILL came back as mirrored twins — forcing hard color/height/pose contrast this time.
  gen "m08_L8A_b08_privacy.png" "$A/carol.png" "$CAROL" "CAROL standing at the front door of her simple doodle house, close to the door, guarded posture with one hand resting on the door frame. Her expression is EMBARRASSED and uncomfortable — a small downturned worried mouth (absolutely NOT smiling), raised anxious eyebrows, her other hand raised to her cheek self-consciously. Her front yard is completely EMPTY — plain flat ground, pointedly nothing in it, no sign, no objects. At the far side of the yard a low simple fence. Peeking over the LEFT side of the fence is ONE nosy neighbor: an ADULT MAN with GREY/SILVER hair, only his head and both hands gripping the fence top are visible, eyes wide and curious, positioned LOW so just his eyes and hair show above the fence. Peeking over the FAR RIGHT side of the fence, much further away and smaller in the frame, is a SEPARATE nosy neighbor: an elderly WOMAN with WHITE hair in a bun, only her head and ONE hand visible, positioned HIGHER so more of her face shows, squinting suspiciously. These two neighbors must have completely different hair color, different hair style, different height in frame, and different hand count — they are two SEPARATE, DIFFERENT-LOOKING individuals, absolutely not mirror images or duplicates of one another. Centered composition on Carol. EXACTLY THREE PEOPLE total." ;;
b09_contract)
  # v8 (Jarrad note): REDESIGNED the shot — flat-on-desk composition failed 3 straight times (model locks the page to a
  # fixed ~15deg lean regardless of instruction, while his reaching arm defaults to ~40deg; neither would budge to match
  # the other). Ray now HOLDS the page up in one hand instead of it lying on the desk, so the page-parallel-to-arm
  # relationship is structural (gripped in his hand) rather than two independent objects that have to coincidentally align.
  gen "m08_L8A_b09_contract.png" "$A/ray.png" "$RAY" "EXACTLY ONE person: RAY seated, holding up a VERTICAL PORTRAIT sheet of paper in front of him with ONE hand gripping its top edge — the page is clearly and noticeably TALLER than it is wide, like an upright sheet of printer paper, NEVER a wide horizontal/landscape rectangle. His gripping arm is bent close to his body, upper arm and forearm both running close alongside the page's long edge as he holds it up near chest height, so the page hangs at the same angle as that arm — nearly upright, tilted only slightly. His OTHER hand holds a pen, reaching to the BOTTOM edge of the page where one empty signature line sits, hovering just above it, hesitant. The plain horizontal placeholder doodle lines fill the rest of the tall page above that bottom signature line. His expression is nervous and hesitant, eyebrows drawn. A simple table is visible behind/beside him for context. Centered composition, generous open cornflower-blue space around. EXACTLY ONE PERSON. NO icons, no UI elements, no logos, no circular graphics or symbols of any kind, no watermark-like shapes anywhere in the image." ;;
*) echo "unknown key $1"; exit 1 ;;
esac
