#!/bin/zsh
# Carol v2 — TWO-person "arguing with the contractor" still (source for the Seedance animated tag).
# Bespoke (not gen_scenes_2B.sh) so the ONE-PERSON clause is replaced by a TWO-person anti-clone guard.
set -u
cd "${BMH_INSTITUTE_ROOT:-$(cd "${0:A:h}/../../.." && pwd)}"
D="docs/design"
OUT="course-assets/scenes/module-02-lesson2B"
STYLE='STYLE: flat sticker-sheet illustration, thick black hand-drawn outlines with a slight wobble, rounded corners, flat fills only (yellow, orange, cream, white, black, light gray) on a single flat cornflower-blue background, no gradients, no texture, no shadows, no lighting, no perspective grid. Icon-level faces: tiny dot eyes, one small nose line, one simple mouth line, minimal features, cylindrical limbs, strong simple silhouettes. Confidently imperfect, hand-drawn. No skin-tone shading (faces are pale near-white cream). No ambient doodles (no hearts, sparkles, music notes, speech bubbles, motion marks). 16:9 wide composition, 1600x900, both figures fully in frame with even cornflower-blue margin, nothing clipped at the edges.'
FILE="m02_L2B_carol_argue.png"
echo "Generate one image with gpt-image-2 and save it to $OUT/$FILE (PNG, 1600x900). Match the attached style references exactly. This is a TWO-PERSON scene. LEFT person = Carol, the SAME character as the attached portrait m02_L2B_carol.png — IDENTICAL face and build: a woman in her sixties, short curly LIGHT-GREY hair, ROUND GLASSES, cream shirt, pale near-white cream face; now looking FRUSTRATED and mid-argument, one hand raised gesturing, the other holding up a single sheet of paper marked LIEN. RIGHT person = a CONTRACTOR (a NEW, different character, clearly NOT Carol): a man in a work CAP and a TOOL BELT, plain cream/orange work clothes, pale near-white cream face; he is ALSO ANGRY — brow furrowed, scowling mouth, one hand thrown out or jabbing a finger back toward Carol, arguing BACK at her (NOT apologizing, NOT sheepish). BOTH people are visibly ANGRY and mid-shout — this is a heated TWO-WAY argument, both scowling at each other. Between them on the ground is the abandoned half-finished repair: a leaning step LADDER and an open PAINT CAN with a brush. Keep the cornflower-blue background BEHIND them completely PLAIN and EMPTY — NO wall, NO gray patch, NO paint patch, nothing on the background. "$STYLE" One short caps word LIEN is allowed on the paper Carol holds; keep letters clean and legible; no other text anywhere. EXACTLY TWO people in the whole image (Carol on the left, the contractor on the right) — no clone, no third person, no duplicate, no reflection; each person has exactly one head and two arms." | \
codex exec -i "$D/style-ref-1.png" -i "$D/style-ref-2.png" -i "$D/cast-board.png" -i "$OUT/m02_L2B_carol.png" --skip-git-repo-check --sandbox workspace-write 2>&1 | tail -4
[ -f "$OUT/$FILE" ] && echo "OK $FILE" || echo "MISSING $FILE"
