#!/bin/zsh
# Lesson TECH-A stills — one lane per image: zsh gen_stills_TECHA.sh <key>
# v4 (Jarrad watch-through redlines 2026-07-10):
#  - LOGOS/PRODUCT UIs use the REAL brand colors from the attached reference — the BMH course
#    palette is COMPLETELY DISREGARDED for logo/UI art (his rule: "use the colors from the
#    logo, don't invent colors"). Scenes still use the course palette.
#  - Sandra visual language = the robot mascot (+ SANDRA wordmark), never an abstract CRM
#    dashboard. Robot identity/colors come from the attached robot anchor and are exempt
#    from the course palette.
#  - Blank panels that "don't convey a message" are out: cards/screens carry pseudo-content
#    (squiggle text lines, house thumbnails, chart shapes) — still NO readable words.
# Model: gpt-image-2 via codex exec.
set -u
cd "${BMH_INSTITUTE_ROOT:-$(cd "${0:A:h}/../../.." && pwd)}"
D="docs/design"
PRIYA="course-assets/scenes/module-12/_anchors/priya.png"
ROBOT="course-assets/scenes/module-techstack/_anchors/sandra-robot.png"
WORDMARK="course-assets/scenes/module-techstack/_anchors/sandra-wordmark.png"
WORDMARK_WHITE="course-assets/scenes/module-techstack/_anchors/sandra-wordmark-white.png"
OUT="course-assets/scenes/module-techstack"
LOGOS="course-assets/logo-callouts/techstack-v3-actual-no-box"
mkdir -p "$OUT"

STYLE='STYLE: flat sticker-sheet doodle illustration on cornflower blue #62b3f3. Thick rounded black hand-drawn outlines with slight wobble. Flat fills only: yellow, orange, cream, white, black. No gradients, no texture, no shadows, no lighting, no perspective, no skin-tone shading. Faces and hands are flat white or cream. Small dot eyes, tiny curved cast-board nose, simple mouth, cylindrical limbs, strong simple silhouettes. No ambient doodles. MINIMALISM: include ONLY the elements listed — no extra props, decor, clutter, or background objects. 16:9 composition, 1600x900 PNG.'
LOGOSTYLE='STYLE: flat sticker doodle REPLICA. Thick rounded hand-drawn outlines with slight wobble, flat fills, confidently imperfect. COLOR RULE (CRITICAL): use the attached logo'"'"'s EXACT own brand colors for the mark and wordmark, and use the BRAND BACKGROUND COLOR specified in the composition — the ENTIRE background is that flat brand color edge to edge (NEVER cornflower blue, NEVER white). The course palette does NOT apply; do NOT recolor, substitute, or invent colors. v5 rule (Jarrad): no white cards/squares, especially behind white text. 16:9 composition, 1600x900 PNG.'
ROBOTID='Sandra the robot mascot, IDENTICAL to the attached robot reference: rounded light-blue robot body, navy rectangular face screen with white almond eyes and a friendly smile, coral ear caps, yellow antenna ball and yellow belly button, swooshy blue hair tuft, small jetpack on her back. Keep her EXACT reference colors (light blue, navy, coral, yellow) — the robot is exempt from the course palette. FACE CONSISTENCY (CRITICAL): her face must be pixel-faithful to the reference — the SAME almond eyes with small lash tips, SAME pupil shape, SAME small smile, nothing redesigned (Jarrad flagged robots drifting between images).'
NOTEXT='No readable text, letters, numbers, logos, app branding, or UI labels anywhere. All screens, panels, cards, and rows are BLANK abstract shapes.'
PSEUDOTEXT='No readable words anywhere: every text-like element is short greeked squiggle lines or dashes (pseudo-text), never real letters or numbers.'

gen() {
  local file="$1"; local desc="$2"; local textrule="${3:-$NOTEXT}"; local style="${4:-$STYLE}"
  [ $# -ge 4 ] && shift 4 || { [ $# -ge 3 ] && shift 3 || shift $#; }
  local refs=(-i "$D/style-ref-1.png" -i "$D/style-ref-2.png" -i "$D/cast-board.png" -i "$D/object-board.png")
  for extra in "$@"; do refs+=(-i "$extra"); done
  for r in "${refs[@]}"; do [ "$r" = "-i" ] && continue; [ -f "$r" ] || { echo "MISSING REF $r"; exit 1; }; done
  echo "=== GEN $file ==="
  echo "Generate one image with gpt-image-2 and save it to $OUT/$file (PNG, 1600x900). Match the attached style references for linework and composition discipline. COMPOSITION: $desc TEXT RULE: $textrule $style" | \
  codex exec "${refs[@]}" --skip-git-repo-check --sandbox workspace-write < /dev/null 2>&1 | tail -3
  [ -f "$OUT/$file" ] && echo "OK $file" || echo "MISSING $file"
}

LOGOCOMP='A doodle-style REPLICA of the attached software logo, drawn LARGE and centered on the cornflower blue field: reproduce the attached logo exactly — same mark, same wordmark layout, and the SAME COLORS as the attached original — redrawn by hand with thick rounded wobbly black outlines. It must be instantly recognizable as the same logo with the same colors. Nothing else in the frame.'

case "$1" in
# ---------- v4 scene redesigns ----------
b02) gen "mTECH_LTECHA_b02_hub.png" "Tech-stack logo grid: a tidy 2-row grid of rounded outlined tiles on the cornflower blue field. EACH TILE'S BACKGROUND IS ITS PRODUCT'S BRAND COLOR (never white): row 1 - Sandra tile deep navy #16234f with the white SANDRA wordmark; PropStream tile vivid orange with white pixel-cloud mark + white wordmark; DealMachine tile soft teal #56C1C6 with WHITE wordmark; Deal Sniper tile deep blue #153A6E with white lettering + scope mark; Dialpad tile very dark plum #160B2E with white lowercase dialpad + light-purple diamond. Row 2 - Closer Lab tile warm peach-cream with black wordmark + orange mic icon; Slack tile aubergine #4A154B with white wordmark + multicolor lozenge mark; Hubstaff tile deep navy #1D2E4A with white wordmark + blue trio mark; BMH Institute tile warm BMH orange with white wordmark + white grad-cap; Google Drive tile dark charcoal #202124 with white wordmark + full-color triangle. Thick wobbly tile outlines. Elements: the grid of 10 colored logo tiles ONLY." "The ONLY text allowed is each logo's own wordmark exactly as in the attached originals, hand-lettered, spelled perfectly. No other text." "$LOGOSTYLE" "$LOGOS/sandra.png" "$LOGOS/propstream.png" "$LOGOS/dealmachine.png" "$LOGOS/deal_sniper.png" "$LOGOS/dialpad.png" "$LOGOS/closer_lab.png" "$LOGOS/slack.png" "$LOGOS/hubstaff.png" "$LOGOS/bmh_institute.png" "$LOGOS/google_drive.png" ;;
b03) gen "mTECH_LTECHA_b03_sandra.png" "$ROBOTID She stands ON THE GROUND at the FAR LEFT EDGE of the frame, facing right. Priya, IDENTICAL to the attached Priya reference (black ponytail, orange headset, yellow top, cream pants), stands ON THE GROUND at the FAR RIGHT EDGE, facing left, HOLDING A CREAM FOLDER of lead sheets against her chest with both hands. Wide empty middle ground between them on a simple ground line — they are about to walk toward each other. Elements: robot Sandra far left + Priya with folder far right + ground line ONLY." "$PSEUDOTEXT" "$STYLE ADDITIONAL CHARACTER RULE: the robot keeps her exact reference colors." "$ROBOT" "$PRIYA" ;;
b04) gen "mTECH_LTECHA_b04_sandra-workflow.png" "$ROBOTID She stands center-right ON THE GROUND with a rectangular chest/stomach compartment door OPEN, revealing neat folder slots inside. ONE single BMH rep — Priya, IDENTICAL to the attached Priya reference (black ponytail, orange headset, yellow top, cream pants) — stands facing her mid-handoff, placing a cream lead folder toward the open compartment. NO other people anywhere in the frame (one rep on screen at a time, Jarrad's direction). Elements: robot Sandra with open compartment + Priya + one folder ONLY." "$PSEUDOTEXT" "$STYLE ADDITIONAL CHARACTER RULE: the robot keeps her exact reference colors." "$ROBOT" "$PRIYA" ;;
b04alt) gen "mTECH_LTECHA_b04alt_sandra-swallow.png" "$ROBOTID She stands center-right with her mouth playfully WIDE OPEN, gulping down a cream lead folder mid-air above her; her hands are raised to catch it. A short queue of three BMH reps approaches from the left, each holding a cream lead folder: Priya first (IDENTICAL to the attached Priya reference), then a rep with short dark curly hair and orange top, then a rep with short gray hair and cream top — all wearing headsets. Elements: robot Sandra swallowing a folder + three reps + their folders ONLY." "$PSEUDOTEXT" "$STYLE ADDITIONAL CHARACTER RULE: the robot keeps her exact reference colors." "$ROBOT" "$PRIYA" ;;
b06) gen "mTECH_LTECHA_b06_propstream.png" "A large Google-Sheets-style doodle spreadsheet filling most of the frame: white sheet, thin grid lines, a green header row, a small green sheet tab at the bottom-left. Eight lead rows, each with a tiny house icon in the first column and squiggle pseudo-text cells across (name, address, status chips in soft yellow/orange). One row is softly highlighted. Elements: the spreadsheet panel ONLY." "$PSEUDOTEXT" "$STYLE SPREADSHEET COLOR EXCEPTION: the sheet header/tab use Google-Sheets green — real product colors apply to product UI." ;;
b07) gen "mTECH_LTECHA_b07_dealmachine.png" "Neighborhood sourcing scene. A simple doodle car drives along a curved street on the blue plane. Three flat cream houses line the street; two carry tiny blank flag markers and light distress cues (one tilted mailbox, one patch of overgrown grass lines). NO phone, NO tray, NO inbox, NO extra panels — the lower-right corner stays empty. Elements: car + street + three houses + two flags + mailbox + grass ONLY." ;;
b14) gen "mTECH_LTECHA_b14_slack.png" "Team communication station. A large chat board with stacked speech bubbles alternating sides (each bubble carries a short squiggle pseudo-text line) and a simple manager avatar circle at the top of the board. NO side column, NO update cards, NO notification bell, NO badges. Elements: chat board + bubbles + avatar circle ONLY." "$PSEUDOTEXT" ;;
b08) gen "mTECH_LTECHA_b08_dealsniper.png" "Offer-decision station. A yellow offer calculator panel (blank button grid), a central orange funnel with three property-profile cards entering the top and ONE emerging below beside an offer sheet, and a simple stopwatch icon with tick marks and a hand (no numerals). EVERY property card is a mini property profile: a small doodle house thumbnail on top and 2-3 squiggle pseudo-text lines below it. The offer sheet also carries squiggle lines. Elements: calculator + funnel + three profile cards in + one profile card out + offer sheet + stopwatch ONLY." "$PSEUDOTEXT" ;;
b09) gen "mTECH_LTECHA_b09_dialpad.png" "Call station centered on a large doodle sketch of the REAL Dialpad inbox UI in Dialpad's own colors: a dark navy/black rounded app window with a thin left sidebar (small icons + the Dialpad purple-to-pink gradient logo dot at top), a main list of 5 unread conversation rows (round avatar circle, squiggle pseudo-text preview, small purple unread badge on the right), and a top search bar. Beside the window, an orange headset rests on the desk. Keep the lower-right ~420px corner pocket clear. Elements: Dialpad window + headset ONLY." "$PSEUDOTEXT" "$STYLE DIALPAD UI COLOR EXCEPTION (CRITICAL): the app window uses Dialpad's REAL colors — dark charcoal/navy surface, white/light row text squiggles, purple-pink gradient logo accent, soft purple badges. The course palette does NOT apply to the app window." ;;
b10) gen "mTECH_LTECHA_b10_coaching.png" "Coaching review scene. A manager (short gray hair, cream cardigan, NO headset) on the left and Priya, IDENTICAL to the attached Priya reference, on the right sit at an orange desk. BETWEEN them stands one clean chart panel: a cream rounded screen showing a simple rising bar chart (4 flat yellow/orange bars) with a small wavy trend line above it. The manager points gently at the chart; Priya nods. Elements: manager + Priya + desk + ONE chart panel ONLY — no other objects on or near the desk." "$NOTEXT" "$STYLE" "$PRIYA" ;;
b11) gen "mTECH_LTECHA_b11_closerlab.png" "An open laptop drawn large and centered, screen filled by a doodle speech-coaching app: top-left a video panel with a simple presenter (head and shoulders, flat cream face) on a blue backdrop; below it a transcript block of squiggle pseudo-text lines with one softly highlighted squiggle; the right third is an insights sidebar with five stacked feedback rows, each row = a small icon (dot, thumbs-up, gauge) + a squiggle label + a short progress bar. Elements: laptop + its screen contents ONLY." "$PSEUDOTEXT" ;;
b12) gen "mTECH_LTECHA_b12_tasks.png" "$ROBOTID She stands at the left proudly holding up a large task-list panel: four rows, each an empty checkbox and a squiggle pseudo-text bar; the third row carries a tiny orange flag marker; the first checkbox is ticked. To the right of the panel floats one small chat-bubble card (two blank bubbles) as the helper channel. Keep the lower-right ~420px corner pocket clear. Elements: robot Sandra + task panel + chat-bubble card ONLY." "$PSEUDOTEXT" "$STYLE ADDITIONAL CHARACTER RULE: the robot keeps her exact reference colors." "$ROBOT" ;;
# ---------- v4 logo cards (TRUE brand colors) ----------
logo_sandra) gen "mTECH_LTECHA_logo_sandra.png" "Sandra logo card, SPACE EDITION (matches the Sandra app login page): background is a DEEP SPACE NAVY (#16234f) field filled with thin white diagonal shooting-star streaks of varying lengths, all angled the same way. The WHITE SANDRA wordmark from the attached white wordmark reference (white italic letters with the speed-streak underline) redrawn doodle-style across the upper-middle. Below it, $ROBOTID drawn full-body FLYING through space with her jetpack flame on, one hand raised in a wave, small motion streaks behind her. Elements: navy space field + shooting-star streaks + white wordmark + flying waving robot ONLY." "The ONLY text allowed is the wordmark SANDRA exactly as attached, hand-lettered, spelled perfectly." "$LOGOSTYLE COLOR OVERRIDE FOR THIS CARD: the background is deep space navy #16234f (NOT cornflower blue) — it replicates the Sandra product's own login screen. White streaks stay thin and subtle." "$WORDMARK_WHITE" "$ROBOT" ;;
logo_sandra_v2) gen "mTECH_LTECHA_logo_sandra_v2.png" "Sandra logo card variant: $ROBOTID drawn LARGE at the left third, full-body, waving enthusiastically with one hand high, jetpack flame gently on. The SANDRA wordmark from the attached wordmark reference sits to her right at center height, redrawn doodle-style in its exact colors. Elements: waving robot + wordmark ONLY." "The ONLY text allowed is the wordmark SANDRA exactly as attached, hand-lettered, spelled perfectly." "$LOGOSTYLE" "$WORDMARK" "$ROBOT" ;;
logo_sandra_v3) gen "mTECH_LTECHA_logo_sandra_v3.png" "Sandra logo card variant: $ROBOTID centered, full-body, both arms up in a cheerful double wave. The SANDRA wordmark from the attached wordmark reference arcs above her, redrawn doodle-style in its exact colors. Elements: waving robot + wordmark ONLY." "The ONLY text allowed is the wordmark SANDRA exactly as attached, hand-lettered, spelled perfectly." "$LOGOSTYLE" "$WORDMARK" "$ROBOT" ;;
logo_propstream) gen "mTECH_LTECHA_logo_propstream.png" "PropStream logo card: the ENTIRE background is flat vivid ORANGE edge to edge. The attached PropStream logo redrawn doodle-style LARGE and centered in WHITE (white pixel-cloud mark + white PROPSTREAM wordmark) with thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (PropStream), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/propstream.png" ;;
logo_dealmachine) gen "mTECH_LTECHA_logo_dealmachine.png" "DealMachine logo card, emulating their brand frame: the ENTIRE background is flat soft TEAL #56C1C6 edge to edge. The wordmark DEALMACHINE redrawn doodle-style LARGE and centered in WHITE (their distinctive letterforms from the attached logo, but white), thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (DEALMACHINE), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/dealmachine.png" ;;
logo_dealsniper) gen "mTECH_LTECHA_logo_dealsniper.png" "Deal Sniper logo card: the ENTIRE background is flat DEEP BLUE #153A6E edge to edge. The attached Deal Sniper logo redrawn doodle-style LARGE and centered: DEAL and SNIPER lettering in WHITE flanking the scope/target mark (scope keeps its navy rings on a white disc so it reads on the dark field), thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (Deal Sniper), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/deal_sniper.png" ;;
logo_dialpad) gen "mTECH_LTECHA_logo_dialpad.png" "Dialpad logo card, emulating their official dark brand frame EXACTLY: the ENTIRE background is very dark plum-black #160B2E edge to edge. Centered: the light-purple #A98FFF four-pointed diamond sitting just left of the lowercase WHITE wordmark dialpad (their rounded sans letterforms), redrawn doodle-style with thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (dialpad, lowercase), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/dialpad.png" ;;
logo_closerlab) gen "mTECH_LTECHA_logo_closerlab.png" "Closer Lab logo card: the ENTIRE background is warm peach-cream #FFE3C2 edge to edge. The attached Closer Lab logo redrawn doodle-style LARGE and centered: orange rounded app tile with white mic doodle, BLACK Closer Lab wordmark + small PRACTICE GYM subtitle, thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (Closer Lab, PRACTICE GYM), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/closer_lab.png" ;;
logo_hubstaff) gen "mTECH_LTECHA_logo_hubstaff.png" "Hubstaff logo card, emulating their official brand frame TO A T: the ENTIRE background is deep navy #1D2E4A. Centered: the blue trio mark (three rounded shapes around a hollow circle, light-blue/mid-blue/royal-blue) beside the WHITE Hubstaff wordmark. Along the very BOTTOM edge: a thin horizontal wavy stripe of color segments left to right (blues, then yellow-orange-red, then greens) with a soft white wave band under it, exactly like their brand banner. Doodle-style thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (Hubstaff), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/hubstaff.png" ;;
logo_slack) gen "mTECH_LTECHA_logo_slack.png" "Slack logo card: the ENTIRE background is Slack aubergine #4A154B edge to edge. The attached Slack logo redrawn doodle-style LARGE and centered: the multicolor lozenge pinwheel mark in its exact four colors above the WHITE Slack wordmark, thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (Slack), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/slack.png" ;;
logo_institute) gen "mTECH_LTECHA_logo_institute.png" "BMH Institute logo card: the ENTIRE background is warm BMH ORANGE edge to edge. The attached BMH Institute logo redrawn doodle-style LARGE and centered: white rounded tile with the orange grad-cap mark, WHITE BMH Institute wordmark + small TRAINING PLATFORM subtitle in white, thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (BMH Institute, TRAINING PLATFORM), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/bmh_institute.png" ;;
logo_drive) gen "mTECH_LTECHA_logo_drive.png" "Google Drive logo card: the ENTIRE background is dark charcoal #202124 edge to edge. The attached Google Drive triangle redrawn doodle-style LARGE and centered in EXACTLY its three colors (green upper-left side, yellow upper-right side, blue bottom band, NO red, no invented colors), with the WHITE wordmark Google Drive below, thick wobbly outlines. Nothing else in the frame." "The ONLY text allowed is the logo's own wordmark (Google Drive), hand-lettered, spelled perfectly." "$LOGOSTYLE" "$LOGOS/google_drive.png" ;;
*) echo "unknown key $1"; exit 1 ;;
esac
