#!/bin/zsh
setopt pipefail
# Beth v2 — interior living room, elderly late-mother's framed portrait on the wall.
# Bespoke (not gen_scenes_2B.sh) so the ONE-PERSON clause allows the mother's memorial PHOTO.
set -u
cd "${BMH_INSTITUTE_ROOT:-$(cd "${0:A:h}/../../.." && pwd)}"
D="docs/design"
OUT="course-assets/scenes/module-02-lesson2B"
STYLE='STYLE: flat sticker-sheet illustration, thick black hand-drawn outlines with a slight wobble, rounded corners, flat fills only (yellow, orange, cream, white, black, light gray) on a single flat cornflower-blue background, no gradients, no texture, no shadows, no lighting, no perspective grid. Icon-level faces: tiny dot eyes, one small nose line, one simple mouth line, minimal features. Confidently imperfect, hand-drawn. No skin-tone shading (faces are pale near-white cream). No ambient doodles (no hearts, sparkles, music notes, speech bubbles, motion marks). 16:9 wide composition, 1600x900, the whole scene fully in frame with even margin, nothing clipped at the edges.'
FILE="m02_L2B_beth_scene.png"
echo "Generate one image with gpt-image-2 and save it to $OUT/$FILE (PNG, 1600x900). Match the attached style references exactly, and the standing woman is the SAME character as the attached portrait m02_L2B_beth.png — IDENTICAL face and build: ONE doodle woman in her early forties, medium build, shoulder-length BLACK hair (NOT grey, NOT elderly), no glasses, white shirt, pale near-white cream face, quiet grieving tired expression. SCENE: Beth stands INSIDE her late mother's quiet LIVING ROOM. Simple flat brand-style room — a plain sofa, a small side table, a rug, a window — clean minimal flat doodle shapes. PROMINENTLY on the WALL BEHIND her hangs a large FRAMED MEMORIAL PORTRAIT of her late mother: a framed head-and-shoulders picture of an ELDERLY woman with short grey/white hair, round gentle face, pale cream face — clearly a photo of someone who has passed. Beth stands quietly, one hand at her side, subdued and grieving, looking around the empty room. Beth is a full or half-length standing figure (NOT a head-and-shoulders portrait). Weary, no smiling. "$STYLE" IMPORTANT: there is EXACTLY ONE living/real person in the scene (Beth). The ONLY other face allowed is the DRAWN portrait inside the picture frame on the wall (the late mother) — that is a framed picture, not a second live person. No other people, no clones, no reflections. No text or words anywhere; the framed photo shows a drawn face, not text." | \
codex exec -i "$D/style-ref-1.png" -i "$D/style-ref-2.png" -i "$D/cast-board.png" -i "$OUT/m02_L2B_beth.png" --skip-git-repo-check --sandbox workspace-write 2>&1 | tail -4
[ -f "$OUT/$FILE" ] && echo "OK $FILE" || echo "MISSING $FILE"
