#!/bin/zsh
# Lesson GLO-A stills — one lane per image: zsh gen_stills_GLOA.sh <key>
# Rules of record (Jarrad 2026-07-09, scene-card-v2.md 1d/1e/1f): minimalism purpose test
# (ONLY listed elements), no code visuals (every board/diagram is art), static text BAKED
# into the art. Model: gpt-image-2 via codex exec. Claude judges, generator never self-grades.
set -u
cd "${BMH_INSTITUTE_ROOT:-$(cd "${0:A:h}/../../.." && pwd)}"
D="docs/design"
PRIYA="course-assets/scenes/module-12/_anchors/priya.png"
SELLER="course-assets/scenes/module-05-lesson5B/_anchors/seller.png"
OUT="course-assets/scenes/module-glossary"
mkdir -p "$OUT"

STYLE='STYLE: flat sticker-sheet doodle illustration on cornflower blue #62b3f3. Thick rounded black hand-drawn outlines with slight wobble. Flat fills only: yellow, orange, cream, white, black. No gradients, no texture, no shadows, no lighting, no perspective, no skin-tone shading. Faces and hands are flat white or cream. Small dot eyes, tiny curved cast-board nose (small hook/comma, never large or pointed), simple mouth, cylindrical limbs, strong simple silhouettes. No ambient doodles. MINIMALISM: include ONLY the elements listed in the composition — no extra props, decor, clutter, or background objects of any kind. 16:9 composition, 1600x900 PNG.'
NOTEXT='No readable text, letters, numbers, logos, labels, or paperwork anywhere.'

gen() {
  local file="$1"; local desc="$2"; local textrule="${3:-$NOTEXT}"
  [ $# -ge 3 ] && shift 3 || shift $#
  local refs=(-i "$D/style-ref-1.png" -i "$D/style-ref-2.png" -i "$D/cast-board.png" -i "$D/object-board.png")
  for extra in "$@"; do refs+=(-i "$extra"); done
  for r in "${refs[@]}"; do [ "$r" = "-i" ] && continue; [ -f "$r" ] || { echo "MISSING REF $r"; exit 1; }; done
  echo "=== GEN $file ==="
  echo "Generate one image with gpt-image-2 and save it to $OUT/$file (PNG, 1600x900). Match the attached style references exactly. COMPOSITION: $desc TEXT RULE: $textrule $STYLE" | \
  codex exec "${refs[@]}" --skip-git-repo-check --sandbox workspace-write < /dev/null 2>&1 | tail -3
  [ -f "$OUT/$file" ] && echo "OK $file" || echo "MISSING $file"
}

case "$1" in
b02) gen "mGLO_LGLOA_b02_library-priya.png" "Library scene. Super tall bookshelves span the ENTIRE width of the frame, edge to edge, floor to top — no gap of empty background anywhere behind them. The shelves are packed with books in REAL varied book colors (deep reds, greens, blues, browns, mixed with some yellow/orange/cream) — this varied-book-color treatment is an authorized exception for the books ONLY; everything else stays on the locked palette. Each spine carries small illegible title-like markings (short scribble lines suggesting a title, NOT real words or letters). Standing in front of the shelves, facing the viewer: Priya, IDENTICAL to the attached Priya reference — black back ponytail, orange phone headset with boom mic, yellow top, cream pants, flat-white face. Elements: full-width shelves + books + Priya ONLY." "No readable text or real letters anywhere; the book spines carry only abstract illegible scribble title marks." "$PRIYA" ;;
b03) gen "mGLO_LGLOA_b03_distressed-property.png" "Vertical split scene, thin divider. LEFT half (a memorial, signifying someone passed away): a framed photograph of an OLDER character — gray hair, kind face, doodle style — standing upright on a small table, with lit candles arranged around the frame and a small vase of flowers beside it. Respectful and calm. RIGHT half (signifying a lost job): a person, IDENTICAL to the attached seller reference (poofy black hair, orange sweater, cream pants), packing up — placing belongings from a desk into an open cardboard box (kraft brown, approved exception). His expression is SUBDUED and somber: small flat straight mouth, NO smile, eyes slightly downcast — he just lost his job. Elements: framed photo + candles + flowers + table on the left; seller + desk + box on the right. NOTHING else." "$NOTEXT" "$SELLER" ;;
b04) gen "mGLO_LGLOA_b04_roadside-car.png" "Roadside scene. A simple flat doodle car sits on the road shoulder with its hood propped open and gray-white SMOKE puffs rising from the engine bay. Nobody around. NO buildings, NO other cars, NO background objects of any kind — just the car on the road with smoke. Elements: road + car + smoke ONLY." ;;
b06) gen "mGLO_LGLOA_b06_as-is-house.png" "Centered interior corner scene. The homeowner, IDENTICAL to the attached seller reference, stands relieved (shoulders relaxed, small smile) beside a simple room corner showing one visible crack in the wall, plain worn flooring, and two moving boxes drawn as KRAFT CARDBOARD: flat brown corrugated cardboard fill with open top flaps and a single tape strip — NOT yellow, NOT gift-like (cardboard brown is an approved one-off object-realism exception). No floor dashes or ground marks. No shame, no mess overload. Elements: seller + cracked wall + floor + two cardboard boxes ONLY." "$NOTEXT" "$SELLER" ;;
b07) gen "mGLO_LGLOA_b07_as-is-call-signal.png" "Vertical split call scene with a thin divider. Both characters drawn the SAME SIZE and same scale. LEFT half: the seller, IDENTICAL to the attached first reference (poofy black hair, orange sweater, cream pants), on a phone INSIDE a distressed house interior — one cracked wall and worn flooring around him, looking relieved. RIGHT half: Priya, IDENTICAL to the attached second reference (black ponytail, orange headset with boom mic, yellow top, cream pants), at an office setting — seated at a simple desk with a monitor, calmly listening and writing on a notepad. No speech bubbles. Elements: divider + seller + phone + cracked interior; Priya + desk + monitor + notepad. NOTHING else." "$NOTEXT" "$SELLER" "$PRIYA" ;;
b08) gen "mGLO_LGLOA_b08_off-market-home.png" "A beautiful, pristine house: lovely exterior, beautiful blooming gardens along the front, and a LONG driveway leading up to it. No yard sign anywhere. No people, no devices, no vehicles. The picture reads: a gorgeous home that simply is not for sale. Elements: house + gardens + long driveway ONLY." ;;
b09) gen "mGLO_LGLOA_b09_bullseye.png" "A large archery bullseye target, centered, filling most of the frame: concentric rings in the palette colors with a clear center bull, and ONE single arrow landed dead-center in the bull. Elements: target + one arrow ONLY." ;;
b10) gen "mGLO_LGLOA_b10_zillow-listing.png" "A doodle ILLUSTRATION of a Zillow real-estate listing page, drawn as a clean rounded listing card occupying the LEFT 55% of the frame; the right 45% is open cornflower blue (a presenter stands there later). The card: hand-lettered Zillow wordmark at top, a large photo area containing a simple doodle house, below it a hand-lettered price line \$200,000, a line reading 3 BD 2 BA, and a fake address line 123 MAPLE ST. Elements: listing card + its contents ONLY." "The ONLY text allowed, hand-lettered in the doodle style, each spelled perfectly: Zillow, \$200,000, 3 BD 2 BA, 123 MAPLE ST. No other text." ;;
b11) gen "mGLO_LGLOA_b11_on-market-flag.png" "EXACTLY three elements. A house in the background. A FOR SALE yard sign planted in front of it. An excited real-estate agent in the foreground celebrating the new listing — arms raised happily, big smile, short dark-brown hair, cream blazer, NO headset, clearly distinct from any BMH cast member. NOTHING else in the scene." "The ONLY text allowed is FOR SALE hand-lettered on the yard sign, spelled perfectly. No other text." ;;
b12) gen "mGLO_LGLOA_b12_listed-expired.png" "Two equal panels split by a thin vertical divider, showing THE SAME HOUSE in both panels (identical shape, door, windows, roof). LEFT panel: the house well-maintained and beautiful — clean walls, tidy yard — with an upright yard sign reading FOR SALE. RIGHT panel: the SAME house after a long time on the market — weeds grown tall in the yard and green vines climbing up the walls — with the seller, IDENTICAL to the attached seller reference (poofy black hair, orange sweater, cream pants), standing outside looking confused (one hand scratching his head), and the same yard sign now drooping/tilted and reading EXPIRED. Elements: two panels of the same house + two signs + seller on the right ONLY." "The ONLY text allowed, hand-lettered: FOR SALE on the left sign and EXPIRED on the right sign, each spelled perfectly. No other text." "$SELLER" ;;
b13) gen "mGLO_LGLOA_b13_dom-calendar.png" "Centered diagram scene: ONE large simple flip-style wall calendar dominating the frame, its face marked with the big hand-lettered text 200 DAYS across the middle. Nothing else in the scene — no listing card, no house, no other objects." "The ONLY text allowed is 200 DAYS hand-lettered on the calendar face, spelled perfectly. No other text, no date numbers." ;;
b14) gen "mGLO_LGLOA_b14_fsbo.png" "Centered front-yard scene. The homeowner, IDENTICAL to the attached seller reference, stands in front of his simple house holding a yard sign that reads FSBO. He looks focused and willing to talk — calm, upright, small smile. No agent anywhere. Elements: house + seller + FSBO sign ONLY." "The ONLY text allowed is the single hand-lettered word FSBO on the sign, spelled perfectly. No other text." "$SELLER" ;;
b15) gen "mGLO_LGLOA_b15_garage-sale.png" "A garage-sale TABLE covered in random doodle household items — a lamp, an old radio, a vase, a small stack of books, a golden trophy, a toaster — each item with a small hanging price tag. The tags read various low prices: \$1, \$3, \$5, \$10 (the trophy carries the \$5 tag). The table scene occupies the LEFT 55% of the frame; the right 45% is open cornflower blue (a presenter stands there later). Elements: table + six items + their price tags ONLY. No people." "The ONLY text allowed is the hand-lettered prices on the tags: \$1, \$3, \$5, \$10 — each spelled perfectly. No other text." ;;
b16) gen "mGLO_LGLOA_b16_contract-to-buyer.png" "Centered three-step deal flow, left to right. Left: a small distressed house (sagging roof) with the homeowner, IDENTICAL to the attached seller reference, beside it. Center: a plain blank contract packet (folder with a blank document corner peeking out) with an arrow in from the left and an arrow out to the right. Right: an end buyer investor — short dark hair, cream jacket, NO headset — receiving the packet with open hands. Elements: house + seller + contract packet + two arrows + buyer ONLY. No tools, no props beyond these." "$NOTEXT" "$SELLER" ;;
b17) gen "mGLO_LGLOA_b17_assignment.png" "Centered rights-transfer scene. Left: a BMH teammate (short dark hair, cream top, orange phone headset) holding out a plain BLANK purchase-agreement card, which passes along an arrow to the right into the hands of the end buyer investor (short dark hair, cream jacket, NO headset). Along a dotted return path below, a small neat stack of GREEN CASH bills (money-green fill — the approved cash exception) travels back from the buyer side to the teammate side, showing the fee. Elements: teammate + blank contract card + arrow + buyer + green cash stack + dotted line ONLY." ;;
b18) gen "mGLO_LGLOA_b18_double-close.png" "Centered scene: two simple closing tables side by side. Left table: the homeowner, IDENTICAL to the attached seller reference, seated across from a BMH teammate (short dark hair, cream top, headset). Right table: the SAME BMH teammate seated across from the end buyer investor (short dark hair, cream jacket, no headset). One plain document folder sits on the left table with a small arrow pointing toward the right table. Elements: two tables + four seated figures + folder + arrow ONLY." "$NOTEXT" "$SELLER" ;;
b19) gen "mGLO_LGLOA_b19_subject-to.png" "Centered handover scene, exactly TWO PEOPLE and ONE KEY. The homeowner, IDENTICAL to the attached seller reference (poofy black hair, orange sweater, cream pants), hands a single large yellow house key to a BMH teammate (short dark hair, cream top, orange headset). NOTHING else in the frame — no documents, no cards, no props of any kind (Jarrad 2026-07-10). Elements: seller + key + teammate ONLY." "$NOTEXT" "$SELLER" ;;
b20) gen "mGLO_LGLOA_b20_seller-financing.png" "Kitchen-table scene. The homeowner, IDENTICAL to the attached seller reference, sits at a simple kitchen table holding a small payment-schedule card (a blank card with three plain empty rows). Across the table, a BMH teammate (short dark hair, cream top, headset) listens calmly. Keep the lower-right ~420px corner pocket clear. Elements: table + seller + schedule card + teammate ONLY." "$NOTEXT" "$SELLER" ;;
b21) gen "mGLO_LGLOA_b21_recap-board.png" "A large simple recap board on a plain stand, occupying the LEFT 55% of the frame; the right 45% is open cornflower blue (a presenter stands there later). The board holds exactly EIGHT rounded rectangular tiles in a tidy 2-column x 4-row grid, each tile hand-lettered with one term: DISTRESSED, OFF-MARKET, AS-IS, WHOLESALE, MLS, EXPIRED, FSBO, GET THEM TALKING. Elements: board + stand + eight tiles ONLY." "The ONLY text allowed, one term hand-lettered per tile, each spelled perfectly: DISTRESSED, OFF-MARKET, AS-IS, WHOLESALE, MLS, EXPIRED, FSBO, GET THEM TALKING. No other text." ;;
*) echo "unknown key $1"; exit 1 ;;
esac
